### ISSUE TITLE
Required Stories

### ISSUE THREAD

**Issue by IsaSam** [IsaSam/Instagram#3]
- [x] User sees app icon in home screen and styled launch screen.
- [x] User can sign up to create a new account using Parse authentication
- [x] User can log in and log out of his or her account
- [x] The current signed in user is persisted across app restarts
- [x] User can take a photo, add a caption, and post it to "Instagram"
- [x] User can view the last 20 posts submitted to "Instagram"
- [x] User can pull to refresh the last 20 posts submitted to "Instagram"
       [X] Auto refresh every minute
- [x] User can tap a post to view post details, including timestamp and caption.

**Comment by codepathreview** [comment]
Looks like you are missing the following required user story:

- User can tap a post to view post details, including timestamp and caption

Your assignment is incomplete until all the [required user stories](https://courses.codepath.com/snippets/ios_university/readme_templates/assignment_1_readme.md) are complete. Once completed, please push your updates, update your README, update your gif and [submit your assignment](https://courses.codepath.com/courses/ios_university/pages/submitting_assignments) again using the submit button on the appropriate assignment page so we can regrade it.

Whenever you make updates to your project that require re-grading, you need to **re-submit** your project using the submit button on the associated assignment page in the course portal. This will flag your project as “updated” on our end and we know to re-grade.

You should re-submit your assignment anytime you:
- Update a previously incomplete assignment
- Add optional and additional features to an already completed assignment 
/cc @codepathreview

**Comment by IsaSam** [comment]
thank's

**Comment by IsaSam** [comment]
completed!
